### ISSUE TITLE
Unexpected interruption when running MD

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/abacus-develop#3581]
### Describe the bug

When I execute an nve MD(near 700 atoms) task through 2 processes, unexpected interruption of the task occurs due to OOM. Conversely, using one process does not occur.

### Expected behavior

At a memory capacity of 250G, it should be executed smoothly.

### To Reproduce

The case includes INPUT, STRU and other output results.
[example.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14112855/example.tar.gz)

### Environment

ABACUS 3.5.2

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
@scott-5, could you have a try for v3.5.4, we have fixed some memory leak issues.

**Comment by scott-5** [comment]
The problem still exist.

**Comment by mohanchen** [comment]
Try using new version, which has several bugs fixed. If problem still exists, try to propose a new issue, thanks a lot! @scott-5
